### ISSUE TITLE
Only WBUS output in entities

### ISSUE THREAD

**Issue by MadsALarsen** [MTrab/webastoconnect#15]
### Describe the issue

I just installed the integration and got the heater in HA, but after setting my Webasto to common output I can no longer see it in HA.
The WBUS output is still there but one is offline.

is there any way to get the 2nd output in HA?

på forhånd tak ;-)

### What version of Home Assistant Core has the issue?

core-2023.10.5

### What type of installation are you running?

Home Assistant Container

### Diagnostics information

none

**Comment by MTrab** [comment]
Will come in a future release

**Comment by MadsALarsen** [comment]
ok thanks for the reply

is it possible (in a later version) to get gps data in HA ?

**Comment by MTrab** [comment]
Already there

**Comment by MTrab** [comment]
If you enable it, that is.

**Comment by MadsALarsen** [comment]
il try that thanks

**Comment by MTrab** [comment]
Would you trust me with the credentials for your account, to try and decode the API for the AUX output?

**Comment by MadsALarsen** [comment]
Ja da, vi har 2 biler men fyr, lige nu har jeg sar den i den nyeste så der er det w-bus men da jeg skrev sidst så sad den i den anden.

jeg flytter den blot tilbage og sender det til dig. 
hvad er din mail?

**Comment by MTrab** [comment]
github_2023 (at) trab.dk kan du bruge :)

**Comment by MadsALarsen** [comment]
Aftale, forsøger at nå det imorgen 👍🏻👍🏻

**Comment by MadsALarsen** [comment]
Mail sendt

**Comment by MadsALarsen** [comment]
> github_2023 (at) trab.dk kan du bruge :)
> 
> Er begge biler på samme konto? Så kan det være jeg kan slå 2 fluer med 1 smæk ;)

har kun et. modul PT men er igang med at undersøge med et mere :-)

**Comment by mudgle** [comment]
Any ETA for aux control? i use the output control for my webasto and cant control it using HA. can see battery, temp and location

**Comment by MTrab** [comment]
Unfortunately no ETA yet, been a bit preoccupied with life :) But rest assured, that it is high on my to-do list

**Comment by MTrab** [comment]
Wee - found some time to implement this.
New release up shortly
