### ISSUE TITLE
just default values 

### ISSUE THREAD

**Issue by gkathan** [MTrab/webastoconnect#43]
### Describe the issue

hi,
I just tried the integration and logged in with my webasto thermo connect Account
* it shows only the default values (13,30V and 21°) 
* but logon seems to be accepted
* thermo connect app and webconnect show real values 
* any advice?
* cheeerz from vienna

### What version of Home Assistant Core has the issue?

core-2024.02.02

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

x

**Comment by MTrab** [comment]
Everything is as it should be.
The values presented are directly from the API - so nothing I can do to fix this.

But if I log into the account it doesn't seem like the device has any internet access.

**Comment by gkathan** [comment]
interesting ... as the app seems to be able to get current values ...


gerold kathan :: +43 699 1973536

**Comment by MTrab** [comment]
If I login to my.webastoconnect.com it's exactly the same values I see - that's where the integration reads the data from.

**Comment by gkathan** [comment]
ok that is weird ...
when I login at my.webadto I get the default values and the message....


gerold kathan :: +43 699 1973536

**Comment by MTrab** [comment]
Yeah - so as you can see, there is nothing to be done for the integration, as it represents the data from the API

**Comment by MTrab** [comment]
I have no idea, as the integration just shows the values from the API (my.webastoconnect.com)

As long as the API doesn't show the correct clues, the integration will not work for you.

**Comment by MTrab** [comment]
Guess the best option is to contact Webasto to hear thier take on why the the webastoconnect page doesn't show the correct values.

I'll close this issue for now, as it has nothing to do with the integration
