### ISSUE TITLE
only default values shown

### ISSUE THREAD

**Issue by gkathan** [MTrab/webastoconnect#44]
### Describe the issue

hi,
just tried your integration with my life webasto thermo connect in my van:
* it only shows default values (21° temp, 13.30)
* real values shown on screenshot of app
* see attached screenshots
any advice?
cheerz
![Screenshot_20240217-064553](https://github.com/MTrab/webastoconnect/assets/6329814/fc715aa6-707e-41d5-9080-8d8da0b79a3f)
![Screenshot_20240217-064524](https://github.com/MTrab/webastoconnect/assets/6329814/7912ba7a-61d4-4c0b-8c87-a8a51fa3e260)
![Screenshot_20240217-064628](https://github.com/MTrab/webastoconnect/assets/6329814/969f2495-bb1c-4d5a-a8c5-072599ee696e)
![Screenshot_20240217-064543](https://github.com/MTrab/webastoconnect/assets/6329814/ba1e83bc-c441-44b7-ac99-cdb878677807)

### What version of Home Assistant Core has the issue?

core-2024.02.02

### What was the last working version of Home Assistant Core?

core-2024.02.02

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

-

**Comment by MTrab** [comment]
It's built for the TCon II so if that's not what you have, then that could be the answer.

**Comment by gkathan** [comment]
> It's built for the TCon II so if that's not what you have, then that could be the answer.

where can I check this ?
I have installed the heater 2 years ago ... latest generation ...

**Comment by MTrab** [comment]
Not even sure it's mentioned in the API, so your best bet is to check your papers from when it was installed - or perhaps check your manual.

**Comment by gkathan** [comment]
it's a tcon2

gerold kathan :: +43 699 1973536
