### ISSUE TITLE
Switch between ventilation mode and heating mode

### ISSUE THREAD

**Issue by veista** [MTrab/webastoconnect#90]
### Describe the feature you wish to make a request for

Thank you for your excellent work on this integration. I don't know if this feature is broken for me or not implemented, but it would be great if I could change between heating mode and ventilation mode via this integration.

**Comment by MTrab** [comment]
This is already implemented

**Comment by veista** [comment]
That was weird. The entity was disabled for some reason by default. I enabled it and reloaded the integration and it now works. Thanks.

**Comment by veista** [comment]
All other confuguration entities were disabled too and some diagnostic entities. I think this is a bug.

**Comment by MTrab** [comment]
Not a bug

**Comment by veista** [comment]
Ok. So what is the reasoning these are disabled by default?

**Comment by MTrab** [comment]
They are non essential for the heater to work as an integration - they are just extras
Just like many other integrations provides extra features as disabled entities
